import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        background: '#ffffff',
        primary: '#151515',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#474746',
        'surface-container': '#fbfaf8',
        'surface-variant': '#f4f3f2',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'inverse-primary': '#c8c6c5',
        'secondary-fixed-dim': '#e9c176',
        'surface-tint': '#5f5e5e',
        'surface-container-low': '#f5f3f3',
        'on-primary-fixed': '#1c1b1b',
        'secondary-container': '#fed488',
        'primary-fixed': '#e5e2e1',
        'on-tertiary-fixed-variant': '#464746',
        'tertiary-fixed': '#e3e2e1',
        'on-secondary-fixed-variant': '#5d4201',
        'on-surface': '#1b1c1c',
        outline: '#a58f54',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#ffdea5',
        'on-primary-container': '#858383',
        secondary: '#8d7a30',
        'surface-dim': '#dbdad9',
        'on-secondary-fixed': '#261900',
        'on-secondary-container': '#785a1a',
        'surface-container-high': '#e9e8e7',
        'inverse-surface': '#303031',
        'on-tertiary': '#ffffff',
        'primary-container': '#1c1b1b',
        surface: '#faf9f8',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#838483',
        'on-background': '#1b1c1c',
        'primary-fixed-dim': '#c8c6c5',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#1a1c1c',
        'tertiary-container': '#1a1c1a',
        'surface-bright': '#fbf9f8',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e3e2e2',
        'inverse-on-surface': '#f2f0f0',
        'on-surface-variant': '#444748',
        tertiary: '#000000',
        'tertiary-fixed-dim': '#c7c6c5',
        'outline-variant': '#c4c7c7',
        'warm-white': '#fdfcfb',
        'matte-black': '#151515',
        'deep-charcoal': '#2d2d2d',
        'soft-beige': '#f5f2ee',
        'gallery-gold': '#d4af37',
        'paper-white': '#f6efdd',
      },
      spacing: {
        'margin-edge': '64px',
        unit: '8px',
        'section-gap': '120px',
        'container-max': '1440px',
        gutter: '32px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      borderRadius: {
        none: '0',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'display-lg': ['var(--font-serif)', 'Playfair Display', 'serif'],
        'headline-lg-mobile': ['var(--font-serif)', 'Playfair Display', 'serif'],
        'headline-lg': ['var(--font-serif)', 'Playfair Display', 'serif'],
        'display-sm': ['var(--font-serif)', 'Playfair Display', 'serif'],
        'title-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        serif: ['var(--font-serif)', 'Georgia', 'serif'],
        sans: ['var(--font-sans)', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '72px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'display-sm': ['48px', { lineHeight: '56px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      boxShadow: {
        soft: '0 30px 40px rgba(0,0,0,0.05)',
        subtle: '0 20px 40px rgba(0,0,0,0.04)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};

export default config;
